require 'sinatra'
require 'slim'
require 'slim/include'

require_relative 'base'
require_relative 'account'
require_relative 'authentication'
require_relative 'register'
require_relative 'folders'
require_relative 'files'
