require_relative 'api_server_wakeup'
require_relative 'retrieve_github_account'
require_relative 'find_authenticated_account'
require_relative 'email_registration_verification'
require_relative 'create_verified_account'
require_relative 'get_all_folders'
require_relative 'get_folder_details'
require_relative 'get_file_details'

require_relative 'create_new_folder'
require_relative 'create_new_file'
require_relative 'add_collaborator_to_folder'
